### ISSUE TITLE
[Question] A way to control menu page positioning individually

### ISSUE THREAD

**Issue by T1mL3arn** [john32b/djFlixel#21]
1. Have a main page with 3 items, centered on a screen (btw would be nice to have more sophisticated control on menu position instead of just bare x and y)
2. Have an option page with, let's say, 10 items
3. The option page has the same positioning as the main page, meaning some of its items are overflowed the screen.

Is it possible to place menu pages individually? So far I have 2 ways, both of them look so-so:

1. Readjust menu position when appropriate page opens
2. Have separate `FlxMenu` object for each page

**Comment by john32b** [comment]
Checkout https://github.com/john32b/djFlixel/discussions/22

Tested this for a bit and it work, I don't think I introduced any bugs, 
if anything broke let me know 🐤
