### ISSUE TITLE
item_update() breakes item alignment

### ISSUE THREAD

**Issue by T1mL3arn** [john32b/djFlixel#24]
```haxe
var menu = new FlxMenu(0,0, 300, 6);

menu.createPage('main')
.add('
  -| create  | link | create_lobby
  -| connect | link | connect_to_lobby
  -| __________ | label | 3 | U
  -| main menu | link | open_main_menu
')
.par({
  pos: 'screen,c,c'
});

menu.STP.align = 'center';
menu.STP.item.text = {
  s: 30,
  a: 'center'
};

// updating menu item on some event
menu.item_update('main', 'connect_to_lobby', item -> {
  item.ID = 'wait_connection';
  item.label = 'connecting..........';
  item.disabled = true;
  item.selectable = false;
});
```

Result:

![image](https://user-images.githubusercontent.com/9349164/233547552-9f6575e5-db4a-4ecd-bef5-1ce0d04d694e.png)

As a workaround (I personally find it better than single item updating if the menu is short) it is possible to create another page with changed item and just open it with `menu.goto('whatever')`.

**Comment by john32b** [comment]
Yep, another bug

When I implemented centered items easing back to baseline, I forgot to change the `MPAGE::item_update(item)` function

it's an easy fix, I already got half of it working.

![hl_ (1)](https://user-images.githubusercontent.com/6090296/233602395-ce5b6ac8-ccde-4b7a-b36d-33b132699864.gif)

also, making a link unselectable while it is currently highlighted I don't think I've tested it,
for now I guess it is safer to just make it "disabled" ?(probably)

I will look into it and push an update later today 🐤

**Comment by john32b** [comment]
hey, check out the new release :: https://github.com/john32b/djFlixel/discussions/25

For the next updates, I'm going to figure out making items unselectable while they are focused

**Comment by john32b** [comment]
OK turns out making an item **unselectable** while it being focused already worked. 😅 
Just make sure to also set **disabled** else it can still receive input and fire triggers.

![hl_ (4)](https://user-images.githubusercontent.com/6090296/234302299-df27b0dc-14a3-4f6c-b23f-3aba4e318bb6.gif)
