### ISSUE TITLE
Empty-label check does not work as expected ?

### ISSUE THREAD

**Issue by T1mL3arn** [john32b/djFlixel#30]
Looks like empty-label check does not work as expected.

```haxe
// for some reason it is empty string
var label = '';

menu.createMenuPag('foo')
  .add('
-| hello | link | hello_link
-| ${label} | link | empty_link
  ');
```

```
Uncaught exception - Wrong MenuItemType at "link" Typo?
```

https://github.com/john32b/djFlixel/blob/495d2a774604f1b3fc4f3463be94c4729836a387/djFlixel/ui/menu/MItemData.hx#L244-L251

Though it caught the problem with empty label, it was not clear at first what is the reason.

**Comment by john32b** [comment]
good catch,
oh yeah, now that I am looking at the code, it completely ignores the empty `| |` fields, as if they don't exist, I don't remember why I did that 🤔. Perhaps to quickly remove the first and last `|` ?

I'll look into this

**Comment by john32b** [comment]
That should do the trick. I don't think I broke anything
