### ISSUE TITLE
Cannot create menu page with all items disabled and unfocused

### ISSUE THREAD

**Issue by T1mL3arn** [john32b/djFlixel#31]
```haxe
var tmenu = new FlxMenu(0, 0, 0, 10);
tmenu.createPage('foobar')

	.add('
		-| foo | link | foo_link | D | U |
		-| bar | link | bar_link | D | U |
		-| action | link | action_link | D | U |
	')
	.par({
		pos: 'screen,c,c'
	});

tmenu.goto('foobar');
```

```
Uncaught exception: Must SetData first
Called from djFlixel.ui.VList.focus(djFlixel/ui/VList.hx:455)
```

**Comment by john32b** [comment]
wow, that is an edge case for sure. It was just the `Unselectable` status for all items, the disabled had nothing to do with it.
Never thought of that scenario.

I took a look 5b410012eda4cf35669d3856b9633c43a5dee2b5. 
Now it doesn't error out and it can still work.
Also I tried making an unselectable item ,selectable again, and it works with some minor extra work. calling the `m.mpActive.item_focus('foo_link');` after making the item selectable.

```haxe
 m = new FlxMenu(0, 0, 0, 10);

m.createPage("main","Main Menu").add('
	-|New Game	| link	| n_game	| D
	-|Menu		| link	| @foobar	| AF')
	.par({ pos:'screen,c,c' });

m.createPage('foobar').add('
		-| foo | link | foo_link | U
		-| bar | link | bar_link | U
		-| action | link | action_link | U ')
	.par({ pos: 'screen,c,c'});

add(m);
m.goto('main');

extra_update = () -> {
	if (D.ctrl.justPressed(DButton.LB)) { // LEFT SHIFT KEY
		m.item_update(null, 'foo_link', (it) -> {
			it.selectable = true;
		});
		m.mpActive.item_focus('foo_link');
	}
}
```

Also made it possible when entering a page with no selectables, you can press *[BACK]* (J key) and go back.
In this vid, first time I am going back to main menu, then I am pressing [left shift] to enable the item

[simplescreenrecorder-2024-01-24_18.32.58.webm](https://github.com/john32b/djFlixel/assets/6090296/7c3d56bc-762e-49f8-a402-280be61c5522)

**Comment by T1mL3arn** [comment]
Now there is a crash with all disabled and unselectable items if I click any item

Neko error stack:
```
Called from djFlixel.ui.VList::update line 447
Called from djFlixel.ui.VList::queue_itemEvent line 370
Called from djFlixel.ui.FlxMenu::on_item_event line 502
Uncaught exception - Invalid field access : ID
```

HashLink error stack:
```
Uncaught exception: Access violation
Called from hl.types.ArrayObj.getDyn(hl/types/ArrayObj.hx:330)
Called from hl.types.ArrayObj.getDyn(hl/types/ArrayObj.hx:330)
Called from hl.types.ArrayObj.getDyn(hl/types/ArrayObj.hx:330)
Called from hl.types.ArrayDyn.getDyn(hl/types/ArrayDyn.hx:62)
Called from djFlixel.ui.VList.~queue_itemEvent.0(djFlixel/ui/VList.hx:370)
Called from djFlixel.ui.VList.update(djFlixel/ui/VList.hx:447)
```

**Comment by john32b** [comment]
oh! I didn't check for the mouse inputs earlier :face_with_spiral_eyes: 
d60d1fbe0e0a3e3ee3f10c23efd74c69e2816bb1
